### ISSUE TITLE
not work in python 3.11.0

### ISSUE THREAD

**Issue by jamestack** [Quart-Addons/quart-babel#2]
Backtrace:

  File "D:\Workspace\python\xxx\xxx\templates\default\xx.html", line 223,
in block 'body'
    <span style="font-size: 24px;display: inline-block;height: 0px; color: #1c2b36;">{{
_(lang_cn(item.country)) }}({{item.phone_code}})</span>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Miniconda3\envs\py31\Lib\site-packages\jinja2\async_utils.py", line 65, in auto_await
    return await t.cast("t.Awaitable[V]", value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot reuse already awaited coroutine

ps:
Work ok in python 3.8

**Comment by jamestack** [comment]
python: 3.11.0
quart version: 0.18.3
quart-babel version: 0.0.3

**Comment by jamestack** [comment]
When i delete "await" in "jinja2\async_utils.py:65"
it's work ok.

**Comment by crood58** [comment]
James,

I apologize that I didn't see this sooner. Is "await" in "jinja2\async_utils.py:65" in the Quart package? 

Chris

**Comment by crood58** [comment]
James, 

Looking into this a little further. I don't think I would recommend using Python 3.11 just yet. I don't if Quart is able to run on 3.11 and plus all the other libraries may not be updated yet for 3.11. I am holding off updating our Quart extensions to 3.11 until I know all their dependencies work with 3.11

Please still confirm what you are talking about with Jinja2 async_utils and if it was part of the Quart package. This could be a problem with 3.11

Chris

**Comment by jamestack** [comment]
> James,
> 
> I apologize that I didn't see this sooner. Is "await" in "jinja2\async_utils.py:65" in the Quart package?
> 
> Chris

yes, the jinja2 package version is 3.1.2
